# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
    
    steps:
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .

      - deploy:
           name: Push application Docker image
           command: |
               echo ${HELLO_TOKEN} | docker login -u "vguar+circleci" --password-stdin quay.io
               docker tag app:latest quay.io/vguar/python-request-get:latest
               docker push quay.io/vguar/python-request-get:latest
