name: Build and Deploy to GKE

on: [push]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  IMAGE: python-request-get

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on:  ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Push Image
      uses: ./.github/actions/docker
      with:
        name: vguar/$IMAGE
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: quay.io 


